### A simple version of an unpooling or opposite pooling layer is called an upsampling layer. It works by repeating the rows and columns of the input.

# How to Use the UpSampling2D Layer?

In [0]:
from numpy import asarray#for making an array using this
from keras.models import Sequential
from keras.layers import UpSampling2D

Using TensorFlow backend.


# For example, an input image with the shape 2×2 would be output as 4×4

In [0]:
 x = asarray([[1,2],      #our input data.
            [3,4]])

In [0]:
print("shape of x:",x.shape)

shape of x: (2, 2)


In [0]:
x = x.reshape(1,2,2,1)   #adding a greyscale to the data and a sample.
                         ## reshape input data into one sample a sample with a channel#####

We can then use the model to make a prediction, that is upsample a provided input image.

...
make a prediction with the model,

prediction = model.predict(X)


In [0]:
model = Sequential() #this allows your model to create layer by layers in a sequential manner##
model.add(UpSampling2D(input_shape = (2,2,1)))  # we use add() function to add layers to our models.



In [0]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 4, 4, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [0]:
#making a prediction with model##
prediction = model.predict(x)

In [0]:
prediction.shape

(1, 4, 4, 1)

In [0]:
#so reshaping it to make print easier.
prediction = prediction.reshape((4,4))   #removing the chanels.

In [0]:
print("prediction",prediction)
print("shape of x after upsampling:",prediction.shape)

prediction [[1. 1. 2. 2.]
 [1. 1. 2. 2.]
 [3. 3. 4. 4.]
 [3. 3. 4. 4.]]
shape of x after upsampling: (4, 4)


# Finally, the model is used to upsample our input, resulting in a doubling of each row and column for our input data, as we expected.

By default, the UpSampling2D will double each input dimension. This is defined by the ‘size‘ argument that is set to the tuple (2,2).

You may want to use different factors on each dimension, such as double the width and triple the height. This could be achieved by setting the ‘size‘ argument to (2,3).The result of applying this operation to a 2×2 image would be a 4×6 output image (e.g. 2×2 and 2×3).

In [0]:

...
# example of using different scale factors for each dimension
model.add(UpSampling2D(size=(2, 3)))

Additionally, by default, the UpSampling2D layer will use a nearest neighbor algorithm to fill in the new rows and columns. This has the effect of simply doubling rows and columns, as described and is specified by the ‘interpolation‘ argument set to ‘nearest‘.

Alternately, a bilinear interpolation method can be used which draws upon multiple surrounding points. This can be specified via setting the ‘interpolation‘ argument to ‘bilinear‘. For example:

In [0]:

...
# example of using bilinear interpolation when upsampling
model.add(UpSampling2D(interpolation='bilinear'))

# There are many interpolation techniques which  will be discussed in this  file  soon